### ISSUE TITLE
Continuous time Lyapunov exponents giving incorrect results for a stable linear equation

### ISSUE THREAD

**Issue by PiotrSokol** [JuliaDynamics/ChaosTools.jl#111]
# Issue Description
I was testing `lyapunovs` and noticed that the results for a non-linear ODE were giving me incorrect results, tested it on a stable linear ODE and found similar behavior. It seems that for long solutions the LE converge to 0.

# Expected Behavior
I tested an equation $\hat{x} = -x$ and expected LE to be -1.
# MWE
```
uisng DynamicalSystems, OrdinaryDiffEq
function linear(dx, x, p, n)
    dx.= -x
    return 
end
ds = ContinuousDynamicalSystem(linear, [0.5,0.5], nothing)
λs = lyapunovs(ds, 1e4, Ttr = 5e0, dt=.1, alg=Tsit5())
```

**Comment by Datseris** [comment]
```julia
julia> trajectory(ds, 1e4)
2-dimensional Dataset{Float64} with 1000001 points
  0.5          0.5
  0.495025     0.495025
  0.490099     0.490099
  0.485223     0.485223
  0.480395     0.480395
  0.475615     0.475615
  0.470882     0.470882
  0.466197     0.466197
  0.461558     0.461558
  0.456966     0.456966
  ⋮
 -1.13248e-7  -1.13248e-7
 -1.1698e-7   -1.1698e-7
 -1.2067e-7   -1.2067e-7
 -1.24317e-7  -1.24317e-7
 -1.27921e-7  -1.27921e-7
 -1.31481e-7  -1.31481e-7
 -1.34995e-7  -1.34995e-7
 -1.38464e-7  -1.38464e-7
 -1.41886e-7  -1.41886e-7
```

The system goes into a fixed point and dynamical evolution stops. Sure, "theoretically" a fixed point has negative exponent, but if I have understood the algorithm behind `lyapunovs` correctly, you will never get the theoretical value for fixed points, because the algorithm relies in evolving the tangent space. The tangent space is not evolved at a fixed point (by definition), thus it is not contracted, thus you don't measure decrease of state space volumes, thus you don't get the "correct" answer.

You should probably use finite time Lyapunov exponents:
```
julia> s = lyapunovs(ds, 1e1, Ttr = 0, dt=.1, alg=Tsit5())
2-element Array{Float64,1}:
 -0.9999999728578159
 -0.9999999728578159
```

**Comment by Datseris** [comment]
Huh, wait a moment... The tangent space _should_ be evolved even at fixed points, right?

The equations of motion are

![image](https://user-images.githubusercontent.com/19669089/81487972-8e988800-9263-11ea-9318-12b2341b9bec.png)


And $J(x)$ is constant matrix. Maybe this is a bug. If you have a look at the source let us know!

**Comment by PiotrSokol** [comment]
Did some sleuthing
```
function linear(dx, x, p, n)
    dx.= -x
    return 
end
tmax = 20000.
transient = 5.  #5e0 works but  5e1 or 5e2 cause the exponents to go to zero
diffeq = Dict("tstops"=>[1.:tmax])
ds = ContinuousDynamicalSystem(linear, [0.5,0.5], [1e0 0.])
λs = lyapunovs(ds, tmax, Ttr = transient, dt=.1, alg=Tsit5(),tstops=1.:tmax)
```
tstops is necessary to ensure correct behavior, but the estimate underflows if Ttr gets large.

The code for Lyapunovs uses the tangent integrator for t < t0 + Ttr which is wasteful and I think it's also where the bug is. 

Wouldn't it be better to remake the ODE problem using a standard DiffEq solver, evolve the trajectory until t>=t0+Ttr and then reinit the tangent integrator? I assume the reorthonormalization step in the tangent integrator loop is correct.

**Comment by Datseris** [comment]
Hm, if I recall correctly, there is a reason we do this: the tangent vectors are aligning with the appropriate directions of expansion and contraction. Thus, once the actual computation starts, after Ttr, you get a much more accurate result.

Have you tested this by not using the tangent integrator? Should be simple to change this, use `integrator` in the Ttr code block and use `integrator.u` as the state to initialize a `tangent_integrator`. 

This sounds like an important bug, but unfortunately I don't have time to solve it :( Therefore I really appreciate any time you spent on it.

**Comment by dpsanders** [comment]
It also depends on the integration algorithm: leaving out the `alg=...` gives the wrong answer (close to 0) even for Ttr=5

**Comment by sbulcsu** [comment]
The same behavior for the largest LE calculation as well even without transient time:

```
function linear!(dx, x, p, n)
    dx .= -x
    return
end
ds = ContinuousDynamicalSystem(linear!, [0.5,0.5], nothing)
λs = lyapunov(ds, 10, Ttr = 0)
```
gives `-0.9999`, while 

`λs = lyapunov(ds, 10, Ttr = 0)`

returns `-0.288`.

**Comment by Datseris** [comment]
This is expected if you use `lyapunov`, provided that you are aware what the algorithm does _exactly_. My bet here is that during the small time interval between successive re-normalizations, the reference trajectory has already reached the fixed point as well as teh test trajectory, adding several 0s to the summation, and as a result biasing the average towards zero. if you add very, very small `d0`, and also have fine temporal resolution, my hypothesis is that what you report here would not happen.

**Comment by rusandris** [comment]
We also did some sleuthing together with @sbulcsu, and we've come to the conclusion that the behaviour of `lyapunov` and `lyapunovs` seen here is not a bug. We think it has to do with how adaptive timestepping works near fixed points. Namely, a solver algorithm with adaptive timestepping enabled will not converge further to the fixed point after it hit the precision determined by abstol and reltol. Thus the reference and the test trajectories would stop approaching each other after some time. Lowering the abstol in the case of this linear system improves the results of the exponents near fixed points (you can see this on the plot: trajectory of one variable of `linear!` on log scale for different abstol values).
![Datseris2](https://user-images.githubusercontent.com/62118955/100386500-34f48100-302e-11eb-99b0-0771013efdff.png)

`lyapunov(ds,50)
-0.28851473801724314`
`lyapunov(ds,50;abstol = 1e-16)
-0.7132827273001122`
`lyapunov(ds,50;abstol = 1e-30)
-0.9999999807856981`

We also tried to fix the issue by replacing step!(pinteg) with step!(pinteg,dt,true) in the source code of `lyapunov`, this way it does give the right exponent, instead of converging to 0. At the moment, it is not possible to use lyapunov with non-adaptive solvers, because of another problem [#111](https://github.com/JuliaDynamics/DynamicalSystems.jl/issues/111) which doesn't allow specifying the dt of the solver.

**Comment by Datseris** [comment]
Thank you so much for taking the time to look here, I really appreciate it. Your comments are extremely helpful. I've been working towards DynamicalSystems.jl 2.0 and already put most deprecation warnings in place. As the change of `dt -> δt` is not possible to be deprecated, I must leave as the last change possible in the master branches. 

Once I have this change in, I will return here and re-try this issue with a fixed step solver.

**Comment by PiotrSokol** [comment]
Random though, this issue can be entire avoided if one were to use Brockett flow to evolve a basis set continuously along with the forward dynamics.

**Comment by dpsanders** [comment]
@PiotrSokol: What is Brockett flow?

**Comment by PiotrSokol** [comment]
Flow on the manifold of orthogonal matrices.

**Comment by dpsanders** [comment]
Thanks. What's a readable reference for that?

**Comment by PiotrSokol** [comment]
There's a bunch of papers that explicitly do this in the context of computing LE's. I quickly googled it, so I  admit I haven't read the [paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.47.3686), but the idea is the same and cropped up a bunch of times.

I'll try to look for a better reference in my files & can potentially help code up the modified tangent system.

**Comment by dpsanders** [comment]
Thanks!

**Comment by Datseris** [comment]
Regarding the method from Weisel: it has been discussed in this paper:

![image](https://user-images.githubusercontent.com/19669089/100649686-1995b880-3343-11eb-8166-c69e21e3868c.png)

One of the authors told me that "they see no reason to implement this approach.", because it causes more trouble than benefits.

**Comment by PiotrSokol** [comment]
@Datseris Cool! I'd be interested in hearing if they have thoughts about the interplay of adaptive time-stepping and the added complexity/computational overhead of the continuous time approach (thanks @rusandris for raising that point!)

**Comment by gerompampastrumf** [comment]
I had the same problem but I solved it by controlling the maximum dt for adaptive timestepping through dtmax argument.
I tested it on the previus example:
```julia
function linear(dx, x, p, n)
    dx.= -x
    return 
end
tmax = 20000.
transient = 5.  #5e0 works but  5e1 or 5e2 cause the exponents to go to zero
diffeq = Dict("tstops"=>[1.:tmax])
ds = ContinuousDynamicalSystem(linear, [0.5,0.5], [1e0 0.])
λs = lyapunov(ds, 50, Ttr = 0,alg=Tsit5(),dtmax=0.1)
```

Which returns -0.9999999957577507

**Comment by Datseris** [comment]
So, @gerompampastrumf , if I read you correctly, a current way to solve this issue is to simply provide a small enough `dtmax`, correct? Seems reasonable, and a simple substitude for not being able to toggle `dt` for non-adaptive methods.
