### ISSUE TITLE
"Improved" estimator of correlation dimension by Judd

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#114]
The following two papers:

Judd, K. (1992). An improved estimator of dimension and some comments on providing
confidence intervals. Physica D: Nonlinear Phenomena, 56(2–3), 216–228. https://doi.org/10.1016/0167-2789(92)90025-I

Judd, K. (1994). Estimating dimension from small samples. Physica D: Nonlinear Phenomena,
71(4), 421–429. https://doi.org/10.1016/0167-2789(94)90008-6

are by Judd, who introduces an improvement of the Grassberger-Procaccia method for estimating the correlation dimension of a set. 

An attempt to implement this is here: https://github.com/JuliaDynamics/ChaosTools.jl/blob/master/src/dimensions/judd.jl

I have implemented almost everything from the papers but I am stuck at the final part, of maximazing 

![image](https://user-images.githubusercontent.com/19669089/83939520-fd72ed80-a7dd-11ea-83c3-039d22aebef3.png)

from the paper... The problem is that `p_i` can potentially get negative values in the optimization process which throws domain error.

---

Would be nice if someone familiar with optimization problems could help out here.

**Comment by Datseris** [comment]
possible idea: an optimizator that works with finite differences instead of derivatives could allow us to use `if` staments, and thus `if` any p_i becomes negative, return automatically `-Inf`.

**Comment by ikottlarz** [comment]
Okay, so I read through the Judd papers and from what I understand, this is really "just" an optimization with constraints (i. e. that the <img src="https://render.githubusercontent.com/render/math?math=p_i>0\forall i"> and <img src="https://render.githubusercontent.com/render/math?math=\sum p_i = 1">, see also the 1994 paper). 
The idea here I think is quite similar to Takens, Judd also does a maximum likelihood estimation, but assuming another distribution: He allows this polynomial "to correct for deviations from the scaling law" (1994 Paper, p. 424, left column, bottom). This makes the problem more complicated than in Takens' case, where you can just easily solve it analytically. To be honest, from my perspective it seems a bit weird to just introduce polynomials without any explanation of what the coefficients mean or anything, but I haven't really read the derivation of this, so I'm probably not the one to judge, here.

So, my idea was now to use `JuMP` to add the constraints stated above to the model and see if that works. Technically, it does, meaning that I don't get any errors, but I now ran into the problem that Judd also stated: That it is not easy to get the optimizer to see the exponential distribution as the "essence", while the polynomial should just correct for deviations. Currently, I'm getting whatever start value I gave for the dimension back, and polynomial coefficients in the order of <img src="https://render.githubusercontent.com/render/math?math=10^8">. Probably due to a large number of maxima in the log-likelihood function. I will update here once I got a grip on how to solve that, but right now I don't really have a good idea here.

**Comment by Datseris** [comment]
Okay great, that is already a big improvement. If the method doesn't work, that is fine. We state it in the paper, that this method is simply not computationally feasible, and too brittle to make it into the comparison!

**Comment by Datseris** [comment]
Also, this thing of including latex in comments is by far the most pro thing I've seen on github. ever.

**Comment by ikottlarz** [comment]
I just googled "github comment latex" or something and copy-pasted from [here](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b) :D

**Comment by Datseris** [comment]
This has been implemented internally on a private (soon to be public) code base, and it is really not worth including in DynamicalSystems.jl (the algorithm is simply not good enough).
