### ISSUE TITLE
Nonlinear Local Lyapunov Exponents

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#137]
Somewhat different concept from the standard Lyapunov exponents (Which stem from linearized dynamics).

Chen, B., Li, J., & Ding, R. (2006). Nonlinear local Lyapunov exponent and atmospheric predictability research. Science in China, Series D: Earth Sciences, 49(10), 1111–1120. https://doi.org/10.1007/s11430-006-1111-0

**Comment by Datseris** [comment]
Here is a simple implementation sketch:

![image](https://user-images.githubusercontent.com/19669089/119259494-e126b700-bbce-11eb-8b8e-d95cfb5fd9d6.png)


At least according to this sketch, this issue is _trivial_ to solve using e.g. `parallel_integrator`.

**Comment by ChenyuDongNUS** [comment]
Hi Dr. Datseris, I came across this paper as well during literature review, if I understand this concept correctly, it is exactly the same with error local growth rate. Am I right?

**Comment by Datseris** [comment]
Hi @ChenyuDongNUS , yes it is exactly the same.

**Comment by Datseris** [comment]
(this is implemented in DynamicalSystems.jl as `local_growth_rates`)

**Comment by ChenyuDongNUS** [comment]
> (this is implemented in DynamicalSystems.jl as `local_growth_rates`)

Thank you very much Dr. Datseris for your kind reply. However, I'm feeling a little bit skeptical of using this method to quantify atmospheric predictability, it shares some similarities with FSLE since they both consider error growth rate outside linear regime. It does make sense for the atmosphere but the way of finding 'local neighbors' in the literature could easily leads to false neighbors.
