### ISSUE TITLE
problem with refining fractal basins of attraction

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#197]
I'm trying to recreate the following figure: 
![image](https://user-images.githubusercontent.com/19669089/126511172-1e742474-42b6-4d13-b990-fbef3922086f.png)

with the new `basins_of_attraction` function. The figure is the basins of the magnetic pendulum projected at the x-y plane. Originally the figure was made with handwritten code that checked convergence to fixed points.

I think a typical use-case of `basins_of_attraction` would be to "refine" basins so that one can examine fractal structures, as in the figure. However, this is not possible with our current design. The "zoomin" for me always gets the same attractor ID, `-1`, as the attractors are outside the grid.

Perhaps it is a good idea to re-design the `basins_of_attraction` function. Instead of giving the value `-1` for _both_ convergence to an attractor outside the grid, _and_ divergence to infinity, `-1` should be reserved _only_ for divergence to infinity. Attractors found outside the grid should/could be counted. Of course the user should be aware to increase the value of the `mx_chk_lost = 100` parameter to much higher iterates (and perhaps we should also do this by default).

The code I'm using to reproduce the above figure is:

```julia
α=0.2; ω=1.0; d=0.3
# grid 1:
gx = gy = range(-5, 5; length = 1500)
# grid 2:
gx = range(1.80, 1.95; length = 1000)
gy = range(0, 0.12; length = 1000)
# compute basins
ma = Systems.magnetic_pendulum(; α, ω, d)
basins, attractors = basins_of_attraction((gx, gy), ma;
mx_chk_att = 1, mx_chk_fnd_att = 30, mx_chk_lost = 1000)
```

For grid 1 it works perfectly and I get the figure above. For grid 2 it is very slow and I get `-1` everywhere.

@awage

**Comment by Datseris** [comment]
Ah, I now realize the problem... Attractors outside the grid are not defined on the grid points, and thus the state machine cannot really comprehent them... Damn. Is there any way we can improve `basins_of_attraction` so that one can "zoom in" into the basins?

**Comment by awage** [comment]
There is a possible solution but maybe it will impact the performances: 

* First we have to allow the user to provide a dictionary with the known attractors as input. 
* In the function ´_identify_basin_of_cell!´ if the current state is outside the grid we can check if it is near one of the input attractor. If it is, we switch state to `att_hit:` and confirm that it is an attractor. We can use `Neighborhood` for this purpose but we have to store the search trees somewhere (in ´bsn_nfo´ for example). 

I do not guarantee that it will work since `basins_of_attraction` only find pieces of the attractor. In some case it may fails, I am not sure at all. It should add about 15~20 lines to the current code. 

Let me know if you have a another idea and we can work on a PR.

**Comment by Datseris** [comment]
I guess this is a fair way to go forwards. If one wants to refine basins, then they already have the attractors on their hands due to the previous call to `basins_of_attraction`. So in essence, the user could provide the `attractors` dictionary they obtained already from the first `basins` call. 

So I think this is a fine modification. But we should add this functionality in such a way that it has no impact on current behavior (i.e. use some smart multiple dispatch approach).
