### ISSUE TITLE
Separate attractor identification of `basins_of_attraction` into its own function

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#229]
My conclusion so far after reading the literature on basins of attraction, basins stability, and all the like, is that our method of identifying the attractors in the function `basins_of_attraction` is the most accurate method one can create. Everything else is less accurate. I'm not including any computational costs regarding memory/cpu time.

Therefore, I believe, it would be useful to have a function that just does what our method does but only in the first step:

1. Define a grid.
2. Provide some arbitrary initial conditions
3. Put these initial conditions through our algorithm until they converge to whatever attractor.
4. Return the attractors found. I.e., the second return argument of `basins_of_attraction`.
5. Stop after the small amount of arbitrary initial conditions is exhausted. This way, you find the atttractors but not their basins.

These accurately identified attractors could then be plugged into wherever else, e.g. again `basins_of_attraction` for more performance, or the new `basin_fractions` of PR#219 

Optimally, we should do this with duplicating as little code as possible.

cc @awage , @KalelR as well.

**Comment by awage** [comment]
I agree. In fact it was my idea to include a similar feature just for bStab #219 implementation. Because once you have the random sampling of the basins and the automatic attractor identification you can perform any kind of metrics on the basins (uncertainty exponent, basin entropy and so forth). 

The identification can be done using a sparse matrix to track the orbit  efficiently. The trajectory would visit only a small part of the phase space. 

You are still tied to the same old problems: 
* you are not sure to have all the attractors. 
* once you have the attractors, how do you match the initial condition? That is, what are the interesting features?

I can start working on this next month. Maybe after #219 has been merged?

**Comment by Datseris** [comment]
Sparse matrix is a really good idea!
