### ISSUE TITLE
Make the `lyapunovs` function return only the k-th larger exponents

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#7]
_From @Datseris on July 19, 2017 12:7_

~~This is extremely simple:~~

The only changes necessary are:
1. in the methods add an optional argument (NOT a keyword) e.g. `k::Int = dimension(ds)`
2. initialize the matrices `Q` and `K` in the `lyapunovs` function to be `eye(k)`
3. For continuous systems make the function `tangentbundle_setup` also depend on `k` and initialize properly and define the e.o.m. properly
4. update the doc string
5. Pull request and BOOM! You contributed!

_Copied from original issue: JuliaDynamics/DynamicalSystems.jl#12_

**Comment by Datseris** [comment]
(also add tests in both discrete and continuous systems lyapunov test files!)

**Comment by Datseris** [comment]
_From @riktimmondal on September 23, 2017 15:35_

I am working on it.

**Comment by Datseris** [comment]
oh COOL!!!!!!!

Just a heads up: you will probably need to create a new method that dispatches based on a 3rd argument (which will be `Int`). 

The reason is, the function currently used `qr_sq` is a specialized version that works only for square matriceis. One would have to use `Base.qr` for the new case...

**Comment by Datseris** [comment]
Update: with the current setup, that `lyapunovs` is using `variational_integrator`, this is an almost trivial thing to do.

**Comment by tkf** [comment]
Cool. Thank you very much for the detailed review of my proposal!

> One of the main goals of this DynamicalSystems.jl ecosystem is to have source code as clear as possible.

This and other similar comments clarify a lot about where DynamicalSystems.jl is going.  Indeed, my proposal doesn't match with this goal. I also think that it is nice to have a well-tested clear code for complex topic like dynamical systems, too.

> from this change the only benefit can be that users get the convergence timeseries of lyapunovs (and then use them for other stuff)?

Almost.  Yea, that was the main goal I was explaining.  But, for example, if you want to lower the number of orthonormalizations as much as possible (because that's the time-consuming part), it is hard to do in one-function approach you are taking.  If you have a low-level API which allows you to step through the algorithm and mutate the temporary objects, it is possible to write up some algorithm to adaptively skip some orthonormalizations (say, when the Lyapunov vectors are not growing).

Anyway, as you said, it's simple to copy the code from ChaosTools.jl and add some lines.  But in my workflow I just want to lower copy-and-paste if possible and import well-tested library.

So, I decided to write my own Julia library for this purpose:
https://github.com/tkf/LyapunovExponents.jl
As the description says, the goal is "a hackable Lyapunov exponents calculator".

I think it's better to implement it once anyway (even if I were to implement this proposal in ChaosTools.jl), since, in my experience, coming up with the right abstraction and interface is hard.  Implementing similar library a few times really helps (not that I want, though).  So, LyapunovExponents.jl is a library for experimenting with the interface which can help exploration in my research.  If it is possible to simplify the code, maybe we can merge LyapunovExponents.jl into DynamicalSystems.jl/ChaosTools.jl.

In case you are interested in:
The main LE calculation is done in core.jl, especially the `step!` function:
https://github.com/tkf/LyapunovExponents.jl/blob/master/src/core.jl
Yes, it's a lot messy than your straight for-loop based code!
There is a small API/internal documentation here:
https://tkf.github.io/LyapunovExponents.jl/latest/api/#Low-level-API-1

**Comment by Datseris** [comment]
Also comment from @RainerEngelken : 

> Just add a parameter for the desired number of Lyapunov exponents to be calculated. As the orthonormalization scales with order n*d^2 where n is the number of degrees of freedom and d is the number of Lyapunov exponents to be calculated, this can result in a speedup of order (n/d)^2, when only the first d Lyapunov exponents are calculated. So in a system of 10^4 equations, when you just need the first 10 Lyapunov exponents, this would be a speedup factor of 10^6.
